---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

GSFA analysis

* [GSFA analysis on LUHMES CROP-seq data](gsfa_LUHMES_data.html)
* [GSFA analysis on CD8+ T Cell (stimulated and unstimulated) CROP-seq data](gsfa_TCells_data.html)

SCEPTRE analysis

* [Test SCEPTRE on example data](test_sceptre.html)
* [SCEPTRE analysis on LUHMES CROP-seq data](sceptre_LUHMES_data.html)
* [SCEPTRE analysis on CD8+ T Cell (stimulated and unstimulated) CROP-seq data](sceptre_TCells_data.html)

MUSIC analysis

* [Test MUSIC on example data](music_example_data.html)
* [MUSIC analysis on LUHMES CROP-seq data](music_LUHMES_data.html)
* [MUSIC analysis on CD8+ T Cell (stimulated) CROP-seq data](music_TCells_data.html)

Two-step clustering analysis

* [Two-step clustering analysis on LUHMES CROP-seq data](twostep_clustering_LUHMES_data.html)
* [Two-step clustering analysis on CD8+ T Cell (stimulated) CROP-seq data](twostep_clustering_TCells_data.html)


Two-step factor analysis using unguided GSFA

* [Two-step unguided GSFA analysis on LUHMES CROP-seq data](unguided_gsfa_LUHMES_data.html)
* [Two-step unguided GSFA analysis on CD8+ T Cell (stimulated) CROP-seq data](unguided_gsfa_Tcells_data.html)

Other analysis

* [Compare GSFA with MAST DEG results](compare_gsfa_mast_degs.html)
* [Distribution of DEGs by expression level bins](check_gsfa_deg_exp.html)
* [Check DEG results for target genes](check_gsfa_targets_degs.html)

